name: babysleeper
description: It helps the baby to sleep.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  number_inc_dec: ^0.8.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/appicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/icons/
    - assets/img/
    - assets/lang/en.json
    - assets/lang/tr.json
